-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives



-- vi: ft=hyprlang

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = 1,
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "altgr-intl",
	},
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("uwsm app -- discord")
end)
