# vi: ft=hyprlang

exec-once = uwsm app -t service -- hyprpolkitagent

exec-once = uwsm app -- waybar
exec-once = uwsm app -- kitty
exec-once = [workspace 2 silent] uwsm app -- firefox
# exec-once = bitwarden
