#!/usr/bin/env fish

cd "$(dirname (realname (status --current-filename)))"
set -l envs (nvim -l ./.emmy-get-env.lua)
if set -q argv[1]
    export $envs
    exec $argv
else
    string join \n -- $envs
end
