-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives



-- vi: ft=hyprlang

-- TODO:

-- - monocle

-- - clipboard manager

-- - https://wiki.hypr.land/0.47.0/Useful-Utilities/

-- - https://wiki.nixos.org/wiki/Default_applications#Configuration
