-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives



-- vi: ft=hyprlang

-- Ignore maximize requests from apps. You'll probably like this.

-- FIXME: Doesnt work?
hl.window_rule({
	match = {},
	suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland

-- FIXME: ?
--hl.window_rule({
--	name = "no_focus_on",
--	match = {
--		match = "pin 0",
--	},
--	-- TODO: review rule: "no_focus on"
--})

hl.window_rule({
	match = { class = "steam" },
	workspace = "name:steam silent",
})

-- windowrule = maximize, class:.*

-- weird white box, begone

hl.window_rule({
	match = { class = "xwaylandvideobridge" },
	opacity = "0 override",
})

hl.window_rule({
	match = { class = "discord" },
	workspace = "name:dc silent",
})
