-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives



-- vi: ft=hyprlang

hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "auto-down",
	scale = 4 / 3,
})

hl.monitor({
	output = "DP-2",
	mode = "preferred",
	position = "auto-up",
	scale = 1,
})

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = 1,
})

-- default

-- This mimics the xwayland scaling of KDE

-- 96 * 4 / 3 = 128

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "altgr-intl",
		touchpad = {
			-- disable_while_typing = no
		},
	},
})

-- TODO: https://www.reddit.com/r/hyprland/comments/1fdamyb/disable_laptop_monitor_when_close_the_lid/

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("bash -c 'echo Xft.dpi: 128 | xrdb -merge'")
end)
