# vi: ft=hyprlang

monitor = eDP-1, preferred, auto-down, {{4 / 3}}
monitor = DP-2, preferred, auto-up, 1
monitor = , preferred, auto, 1 # default

# This mimics the xwayland scaling of KDE
exec-once = bash -c 'echo "Xft.dpi: 128" | xrdb -merge'  # 96 * 4 / 3 = 128
xwayland {
  force_zero_scaling = true
}
input {
    kb_layout = us
    kb_variant = altgr-intl
    touchpad {
        # disable_while_typing = no
    }
}

# TODO: https://www.reddit.com/r/hyprland/comments/1fdamyb/disable_laptop_monitor_when_close_the_lid/
