-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives



-- vi: ft=hyprlang

-- TODO: Keychords (https://www.youtube.com/watch?v=jhIr9VN2znI)

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"
local shiftMod = mainMod .. " + SHIFT"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("uwsm-app -- kitty"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

-- TODO: manual review (unknown dispatcher: forcekillactive)
-- hl.bind("$mainMod + SHIFT + C", hl.dsp.forcekillactive())

-- FIXME: This kills all os-windows for kitty??

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd('rofi -show drun -theme material -run-command "uwsm-app -- {cmd}"'))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- fullscreen above bar

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

-- fullscreen while keeping bar

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("killall -SIGUSR1 . waybar-wrapped"))

-- toggle waybar

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "p", hl.dsp.focus({ workspace = "name:steam" }))

hl.bind(mainMod .. " + " .. "d", hl.dsp.focus({ workspace = "name:dc" }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "p", hl.dsp.window.move({ workspace = "name:steam" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "d", hl.dsp.window.move({ workspace = "name:dc" }))

-- TODO: Implement minimize window using special workspaces

-- https://wiki.hypr.land/Configuring/Uncommon-tips--tricks/#minimize-windows-using-special-workspaces

-- bind = $mainMod, S, togglespecialworkspace, magic

-- bind = $mainMod, S, movetoworkspace, +0

-- bind = $mainMod, S, togglespecialworkspace, magic

-- bind = $mainMod, S, movetoworkspace, special:magic

-- bind = $mainMod, S, togglespecialworkspace, magic

-- Relative move between existing workspaces

-- bind = $mainMod, tab, workspace, e+1

-- bind = $mainMod SHIFT, tab, workspace, e-1

-- Screenshot a region (Print)

hl.bind("PRINT", hl.dsp.exec_cmd("env HYPRSHOT_DIR=local_var_HOME/Pictures/Screenshots hyprshot --freeze -m region"))

-- Screenshot a monitor (Super+Print)

hl.bind(mainMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot --freeze -m output"))

-- Screenshot a window (Super+Shift+Print)

hl.bind(shiftMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot --freeze -m window"))

-- Move/resize windows with mainMod & dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "mouse:272", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
