-- Generated by hyprconf2lua v1.2.1
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives



-- vi: ft=hyprlang

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 0,
		gaps_out = 0,
		border_size = 1,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = {
				colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
				angle = 45,
			},
			inactive_border = "rgba(595959aa)",
		},
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 0,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.1,
		-- https://wiki.hypr.land/Configuring/Performance/#how-do-i-make-hyprland-draw-as-little-power-as-possible-on-my-laptop
		shadow = {
			enabled = false,
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = false,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = false,
	},
})

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- FIXME: Get this working again under lua

hl.workspace_rule({
	workspace = "w[tv1]",
	gaps_out = 0,
	gaps_in = 0,
})

hl.workspace_rule({
	workspace = "f[1]",
	gaps_out = 0,
	gaps_in = 0,
})

hl.window_rule({
	match = { workspace = "w[tv1]" },
	rounding = 0,
	border_size = 0,
})

hl.window_rule({
	match = { workspace = "f[1]" },
	border_size = 0,
	rounding = 0,
})

-- FIXME: Get this working again under lua

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
	},
})

-- FIXME: Get this working again under lua

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

-- master {

--     new_status = master

-- }

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
		-- vfr = true
	},
})

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)
