# vi: ft=hyprlang

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

windowrule = workspace name:steam silent, match:class steam

# windowrule = maximize, class:.*

# weird white box, begone
windowrule = opacity 0 override, match:class xwaylandvideobridge

windowrule = workspace match:name dc silent, match:class discord
